services:
  - type: web
    name: ai-prompt-manager
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://ai-prompt-manager-ssxy.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null

databases:
  - name: ai-prompt-manager-db
    databaseName: ai_prompt_manager
    user: ai_prompt_manager_user
